Add include directories for OpenTimeConfig.cmake/OpenTimelineIOConfig…
PixarAnimationStudios/OpenTimelineIO pull request #916
Opened 2021-03-12 18:13 UTC by darbyjohnston

```Fixes #915```

This change adds the include directories to the auto-generated OpenTimeConfig.cmake/OpenTimelineIOConfig.cmake files so that C++ projects using OTIO can find the header files.

2021-03-12 18:57 UTC, meshula requested changes
Thanks for catching this! One little twist to address...

2021-03-12 19:00 UTC, meshula commented on src/opentimelineio/CMakeLists.txt
> +           INCLUDES DESTINATION "${OTIO_RESOLVED_CXX_INSTALL_DIR}/include;${OTIO_RESOLVED_CXX_INSTALL_DIR}/include/opentimelineio/deps"
Also, not related to your change, just thinking out loud, we haven't considered "what if the user wants our any, but not our optional, or vice versa?" I hope we can remove these dependencies before it actually becomes an issue!

2021-03-12 19:17 UTC, darbyjohnston commented on src/opentimelineio/CMakeLists.txt
> +           INCLUDES DESTINATION "${OTIO_RESOLVED_CXX_INSTALL_DIR}/include;${OTIO_RESOLVED_CXX_INSTALL_DIR}/include/opentimelineio/deps"
Good point, I added a conditional for OTIO_DEPENDENCIES_INSTALL.

2021-03-12 19:33 UTC, darbyjohnston commented on src/opentimelineio/CMakeLists.txt
> +           INCLUDES DESTINATION "${OTIO_RESOLVED_CXX_INSTALL_DIR}/include;${OTIO_RESOLVED_CXX_INSTALL_DIR}/include/opentimelineio/deps"
The documentation mentions that any/optional are provided in C++17? If CMAKE_CXX_STANDARD was bumped up to 17 they could be removed...

2021-03-13 00:06 UTC, meshula approved these changes

2021-03-13 00:06 UTC, merged

2021-03-13 00:07 UTC, meshula commented
Thanks!